// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type Supplier struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Country *string `json:"country,omitempty"`
}

func (Supplier) IsEntity() {}
