// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Contract struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	Supplier     *Supplier `json:"supplier"`
	Responsibles []*User   `json:"responsibles,omitempty"`
}

func (Contract) IsEntity() {}

type Query struct {
}

type Supplier struct {
	ID        string      `json:"id"`
	Contracts []*Contract `json:"contracts,omitempty"`
}

func (Supplier) IsEntity() {}

type User struct {
	ID string `json:"id"`
}

func (User) IsEntity() {}
